name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Requisit: Imatge docker de python
    container: python:3.10

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Analitzador de codi estàtic (pylint)
      run: |
        # Executa pylint sobre els fitxers .py. Ajusta el patró si cal.
        # El '|| true' evita que el pipeline falli si el pylint troba warnings no crítics
        pylint $(git ls-files '*.py') || true

    - name: Executar test i el seu coverage
      run: |
        # Executa pytest amb l'informe de cobertura
        pytest --cov=./ --cov-report=term-missing
